dataset: AWA1
syn_num: 1800
attSize: 85
nz: 85
nhF: 2048
ins_weight: 0.001
cls_weight: 0.001
gem_weight: 0.001
manualSeed: 9182
nclass_all: 50
nclass_seen: 40
lamd1: 1.0
lamd2: 0.1
lamd3: 0.2
batch_size: 2048
nepoch: 150
ins_temp: 0.3
cls_temp: 0.1
lr_decay_epoch: 100
embedSize: 4096





