dataset: CUB
syn_num: 300
attSize: 1024
nz: 1024
nhF: 2048
ins_weight: 0.01
cls_weight: 0.01
gem_weight: 0.01
manualSeed: 3483
nclass_all: 200
nclass_seen: 150
lamd1: 1.0
lamd2: 0.1
lamd3: 0.2
nepoch: 800
class_embedding: 'sent'
batch_size: 2048
ins_temp: 0.05
lr_decay_epoch: 200
embedSize: 4096