dataset: FLO
syn_num: 200
attSize: 1024
nz: 512
nhF: 1024
ins_weight: 0.001
cls_weight: 0.01
gem_weight: 0.001
manualSeed: 806
nclass_all: 102
nclass_seen: 82
lamd1: 1.0
lamd2: 0.1
lamd3: 0.2
batch_size: 3072
nepoch: 800
ins_temp: 0.2
cls_temp: 1.0
lr_decay_epoch: 200
embedSize: 4096